# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QSplitter, QStackedWidget, QStatusBar,
    QToolBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1044, 674)
        icon = QIcon()
        icon.addFile(u":/icons/pulse_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.action_new_project = QAction(MainWindow)
        self.action_new_project.setObjectName(u"action_new_project")
        icon1 = QIcon()
        icon1.addFile(u":/icons/common/new_file.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_project.setIcon(icon1)
        self.action_open_project = QAction(MainWindow)
        self.action_open_project.setObjectName(u"action_open_project")
        icon2 = QIcon()
        icon2.addFile(u":/icons/common/import.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_open_project.setIcon(icon2)
        self.action_export_png = QAction(MainWindow)
        self.action_export_png.setObjectName(u"action_export_png")
        icon3 = QIcon()
        icon3.addFile(u":/icons/save_image.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_export_png.setIcon(icon3)
        self.action_reset = QAction(MainWindow)
        self.action_reset.setObjectName(u"action_reset")
        icon4 = QIcon()
        icon4.addFile(u":/icons/common/reset-image.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_reset.setIcon(icon4)
        self.action_save_project = QAction(MainWindow)
        self.action_save_project.setObjectName(u"action_save_project")
        self.action_save_project.setEnabled(True)
        icon5 = QIcon()
        icon5.addFile(u":/icons/common/save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_save_project.setIcon(icon5)
        self.action_save_project_as = QAction(MainWindow)
        self.action_save_project_as.setObjectName(u"action_save_project_as")
        self.action_save_project_as.setEnabled(True)
        icon6 = QIcon()
        icon6.addFile(u":/icons/common/save_as.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_save_project_as.setIcon(icon6)
        self.action_import_geometry = QAction(MainWindow)
        self.action_import_geometry.setObjectName(u"action_import_geometry")
        self.action_import_geometry.setEnabled(True)
        icon7 = QIcon()
        icon7.addFile(u":/icons/common/geometry_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_import_geometry.setIcon(icon7)
        self.action_import_pcf = QAction(MainWindow)
        self.action_import_pcf.setObjectName(u"action_import_pcf")
        self.action_import_pcf.setEnabled(True)
        self.actionfiles = QAction(MainWindow)
        self.actionfiles.setObjectName(u"actionfiles")
        self.actionfiles.setEnabled(False)
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        icon8 = QIcon()
        icon8.addFile(u":/icons/common/exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_exit.setIcon(icon8)
        self.action_plot_raw_lines = QAction(MainWindow)
        self.action_plot_raw_lines.setObjectName(u"action_plot_raw_lines")
        self.action_plot_lines = QAction(MainWindow)
        self.action_plot_lines.setObjectName(u"action_plot_lines")
        self.action_plot_mesh = QAction(MainWindow)
        self.action_plot_mesh.setObjectName(u"action_plot_mesh")
        self.action_plot_lines_with_cross_section = QAction(MainWindow)
        self.action_plot_lines_with_cross_section.setObjectName(u"action_plot_lines_with_cross_section")
        self.action_plot_cross_section = QAction(MainWindow)
        self.action_plot_cross_section.setObjectName(u"action_plot_cross_section")
        self.action_plot_cross_section.setEnabled(True)
        self.action_plot_material = QAction(MainWindow)
        self.action_plot_material.setObjectName(u"action_plot_material")
        self.action_plot_material.setEnabled(True)
        self.action_plot_fluid = QAction(MainWindow)
        self.action_plot_fluid.setObjectName(u"action_plot_fluid")
        self.action_plot_fluid.setEnabled(True)
        self.action_user_preferences = QAction(MainWindow)
        self.action_user_preferences.setObjectName(u"action_user_preferences")
        icon9 = QIcon()
        icon9.addFile(u":/icons/common/user_preferences_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_user_preferences.setIcon(icon9)
        self.action_plot_geometry_editor = QAction(MainWindow)
        self.action_plot_geometry_editor.setObjectName(u"action_plot_geometry_editor")
        self.action_create_edit_geometry = QAction(MainWindow)
        self.action_create_edit_geometry.setObjectName(u"action_create_edit_geometry")
        self.action_edit_geometry = QAction(MainWindow)
        self.action_edit_geometry.setObjectName(u"action_edit_geometry")
        self.action_set_project_attributes = QAction(MainWindow)
        self.action_set_project_attributes.setObjectName(u"action_set_project_attributes")
        self.action_set_geometry_file = QAction(MainWindow)
        self.action_set_geometry_file.setObjectName(u"action_set_geometry_file")
        self.action_structural_model_info = QAction(MainWindow)
        self.action_structural_model_info.setObjectName(u"action_structural_model_info")
        self.action_acoustic_model_info = QAction(MainWindow)
        self.action_acoustic_model_info.setObjectName(u"action_acoustic_model_info")
        self.action_check_beam_criteria = QAction(MainWindow)
        self.action_check_beam_criteria.setObjectName(u"action_check_beam_criteria")
        self.action_select_analysis_type = QAction(MainWindow)
        self.action_select_analysis_type.setObjectName(u"action_select_analysis_type")
        self.action_analysis_setup = QAction(MainWindow)
        self.action_analysis_setup.setObjectName(u"action_analysis_setup")
        self.action_run_analysis = QAction(MainWindow)
        self.action_run_analysis.setObjectName(u"action_run_analysis")
        self.action_plot_structural_mode_shapes = QAction(MainWindow)
        self.action_plot_structural_mode_shapes.setObjectName(u"action_plot_structural_mode_shapes")
        self.action_plot_displacement_field = QAction(MainWindow)
        self.action_plot_displacement_field.setObjectName(u"action_plot_displacement_field")
        self.action_plot_structural_frequency_response = QAction(MainWindow)
        self.action_plot_structural_frequency_response.setObjectName(u"action_plot_structural_frequency_response")
        self.action_plot_reactions_frequency_response = QAction(MainWindow)
        self.action_plot_reactions_frequency_response.setObjectName(u"action_plot_reactions_frequency_response")
        self.action_plot_stress_field = QAction(MainWindow)
        self.action_plot_stress_field.setObjectName(u"action_plot_stress_field")
        self.action_plot_stress_frequency_response = QAction(MainWindow)
        self.action_plot_stress_frequency_response.setObjectName(u"action_plot_stress_frequency_response")
        self.action_plot_acoustic_pressure_field = QAction(MainWindow)
        self.action_plot_acoustic_pressure_field.setObjectName(u"action_plot_acoustic_pressure_field")
        self.action_plot_acoustic_frequency_response = QAction(MainWindow)
        self.action_plot_acoustic_frequency_response.setObjectName(u"action_plot_acoustic_frequency_response")
        self.action_plot_acoustic_frequency_response_function = QAction(MainWindow)
        self.action_plot_acoustic_frequency_response_function.setObjectName(u"action_plot_acoustic_frequency_response_function")
        self.acoustic_plot_acoustic_delta_pressures = QAction(MainWindow)
        self.acoustic_plot_acoustic_delta_pressures.setObjectName(u"acoustic_plot_acoustic_delta_pressures")
        self.action_plot_transmission_loss_or_attenuation = QAction(MainWindow)
        self.action_plot_transmission_loss_or_attenuation.setObjectName(u"action_plot_transmission_loss_or_attenuation")
        self.action_play_pause_animation = QAction(MainWindow)
        self.action_play_pause_animation.setObjectName(u"action_play_pause_animation")
        self.action_animation_settings = QAction(MainWindow)
        self.action_animation_settings.setObjectName(u"action_animation_settings")
        self.action_help = QAction(MainWindow)
        self.action_help.setObjectName(u"action_help")
        self.action_about_openpulse = QAction(MainWindow)
        self.action_about_openpulse.setObjectName(u"action_about_openpulse")
        self.action_show_mesh_data = QAction(MainWindow)
        self.action_show_mesh_data.setObjectName(u"action_show_mesh_data")
        self.action_show_mesh_data.setCheckable(True)
        self.action_show_mesh_data.setChecked(False)
        icon10 = QIcon()
        icon10.addFile(u":/icons/common/show_mesh_points.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_show_mesh_data.setIcon(icon10)
        self.action_show_lines = QAction(MainWindow)
        self.action_show_lines.setObjectName(u"action_show_lines")
        self.action_show_lines.setCheckable(True)
        self.action_show_lines.setChecked(True)
        icon11 = QIcon()
        icon11.addFile(u":/icons/common/show_lines.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_show_lines.setIcon(icon11)
        self.action_show_tubes = QAction(MainWindow)
        self.action_show_tubes.setObjectName(u"action_show_tubes")
        self.action_show_tubes.setCheckable(True)
        self.action_show_tubes.setChecked(True)
        icon12 = QIcon()
        icon12.addFile(u":/icons/common/show_tubes.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_show_tubes.setIcon(icon12)
        self.action_show_symbols = QAction(MainWindow)
        self.action_show_symbols.setObjectName(u"action_show_symbols")
        self.action_show_symbols.setCheckable(True)
        self.action_show_symbols.setChecked(True)
        icon13 = QIcon()
        icon13.addFile(u":/icons/common/show_symbols.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_show_symbols.setIcon(icon13)
        self.action_hide_selection = QAction(MainWindow)
        self.action_hide_selection.setObjectName(u"action_hide_selection")
        self.action_unhide_all = QAction(MainWindow)
        self.action_unhide_all.setObjectName(u"action_unhide_all")
        self.action_export_geometry = QAction(MainWindow)
        self.action_export_geometry.setObjectName(u"action_export_geometry")
        icon14 = QIcon()
        icon14.addFile(u":/icons/send_to_disk.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_export_geometry.setIcon(icon14)
        self.action_set_dark_theme = QAction(MainWindow)
        self.action_set_dark_theme.setObjectName(u"action_set_dark_theme")
        icon15 = QIcon()
        icon15.addFile(u":/icons/common/moon_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_set_dark_theme.setIcon(icon15)
        self.action_set_light_theme = QAction(MainWindow)
        self.action_set_light_theme.setObjectName(u"action_set_light_theme")
        icon16 = QIcon()
        icon16.addFile(u":/icons/common/sun_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_set_light_theme.setIcon(icon16)
        self.action_remove_themes = QAction(MainWindow)
        self.action_remove_themes.setObjectName(u"action_remove_themes")
        self.action_show_transparent = QAction(MainWindow)
        self.action_show_transparent.setObjectName(u"action_show_transparent")
        self.action_show_transparent.setCheckable(True)
        self.action_show_transparent.setChecked(False)
        icon17 = QIcon()
        icon17.addFile(u":/icons/common/mesh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_show_transparent.setIcon(icon17)
        self.action_select_elements = QAction(MainWindow)
        self.action_select_elements.setObjectName(u"action_select_elements")
        self.action_select_elements.setCheckable(True)
        self.action_export_pcf = QAction(MainWindow)
        self.action_export_pcf.setObjectName(u"action_export_pcf")
        self.action_geometry_editor_help = QAction(MainWindow)
        self.action_geometry_editor_help.setObjectName(u"action_geometry_editor_help")
        self.action_section_plane = QAction(MainWindow)
        self.action_section_plane.setObjectName(u"action_section_plane")
        self.action_section_plane.setCheckable(True)
        icon18 = QIcon()
        icon18.addFile(u":/icons/common/section_plane_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_section_plane.setIcon(icon18)
        self.action_zoom = QAction(MainWindow)
        self.action_zoom.setObjectName(u"action_zoom")
        icon19 = QIcon()
        icon19.addFile(u":/icons/common/zoom_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_zoom.setIcon(icon19)
        self.action_pulsation_suppression_device_editor = QAction(MainWindow)
        self.action_pulsation_suppression_device_editor.setObjectName(u"action_pulsation_suppression_device_editor")
        self.action_show_geometry_data = QAction(MainWindow)
        self.action_show_geometry_data.setObjectName(u"action_show_geometry_data")
        self.action_show_geometry_data.setCheckable(True)
        icon20 = QIcon()
        icon20.addFile(u":/icons/common/show_geometry_points.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_show_geometry_data.setIcon(icon20)
        self.action_plot_default_color = QAction(MainWindow)
        self.action_plot_default_color.setObjectName(u"action_plot_default_color")
        self.action_geometry_editor_workspace = QAction(MainWindow)
        self.action_geometry_editor_workspace.setObjectName(u"action_geometry_editor_workspace")
        icon21 = QIcon()
        icon21.addFile(u":/icons/common/model_settings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_geometry_editor_workspace.setIcon(icon21)
        self.action_model_setup_workspace = QAction(MainWindow)
        self.action_model_setup_workspace.setObjectName(u"action_model_setup_workspace")
        icon22 = QIcon()
        icon22.addFile(u":/icons/common/engineering.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_model_setup_workspace.setIcon(icon22)
        self.action_results_workspace = QAction(MainWindow)
        self.action_results_workspace.setObjectName(u"action_results_workspace")
        icon23 = QIcon()
        icon23.addFile(u":/icons/common/calculate.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_results_workspace.setIcon(icon23)
        self.action_check_refprop = QAction(MainWindow)
        self.action_check_refprop.setObjectName(u"action_check_refprop")
        self.action_pulsation_damper_editor = QAction(MainWindow)
        self.action_pulsation_damper_editor.setObjectName(u"action_pulsation_damper_editor")
        self.action_capture_image = QAction(MainWindow)
        self.action_capture_image.setObjectName(u"action_capture_image")
        icon24 = QIcon()
        icon24.addFile(u":/icons/cube-scan.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_capture_image.setIcon(icon24)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(3)
        self.setup_widgets_stack = QStackedWidget(self.splitter)
        self.setup_widgets_stack.setObjectName(u"setup_widgets_stack")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setup_widgets_stack.sizePolicy().hasHeightForWidth())
        self.setup_widgets_stack.setSizePolicy(sizePolicy)
        self.setup_widgets_stack.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.setup_widgets_stack.setStyleSheet(u"")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setAutoFillBackground(False)
        self.page.setStyleSheet(u"background: red;")
        self.setup_widgets_stack.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setStyleSheet(u"background: blue;")
        self.setup_widgets_stack.addWidget(self.page_2)
        self.splitter.addWidget(self.setup_widgets_stack)
        self.render_widgets_stack = QStackedWidget(self.splitter)
        self.render_widgets_stack.setObjectName(u"render_widgets_stack")
        sizePolicy.setHeightForWidth(self.render_widgets_stack.sizePolicy().hasHeightForWidth())
        self.render_widgets_stack.setSizePolicy(sizePolicy)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setStyleSheet(u"background: red;")
        self.render_widgets_stack.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4.setStyleSheet(u"background: black;")
        self.render_widgets_stack.addWidget(self.page_4)
        self.splitter.addWidget(self.render_widgets_stack)

        self.verticalLayout.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1044, 24))
        self.menu_project = QMenu(self.menubar)
        self.menu_project.setObjectName(u"menu_project")
        self.menu_recent = QMenu(self.menu_project)
        self.menu_recent.setObjectName(u"menu_recent")
        icon25 = QIcon()
        icon25.addFile(u":/icons/common/recent.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.menu_recent.setIcon(icon25)
        self.menu_plots = QMenu(self.menubar)
        self.menu_plots.setObjectName(u"menu_plots")
        self.menu_model_info = QMenu(self.menubar)
        self.menu_model_info.setObjectName(u"menu_model_info")
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_general_settings = QMenu(self.menubar)
        self.menu_general_settings.setObjectName(u"menu_general_settings")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tool_bar = QToolBar(MainWindow)
        self.tool_bar.setObjectName(u"tool_bar")
        self.tool_bar.setStyleSheet(u"QToolBar {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #888888;\n"
"}\n"
"")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.tool_bar)
        self.workspaces_toolbar = QToolBar(MainWindow)
        self.workspaces_toolbar.setObjectName(u"workspaces_toolbar")
        self.workspaces_toolbar.setStyleSheet(u"QToolBar {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #888888;\n"
"}\n"
"")
        self.workspaces_toolbar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.workspaces_toolbar)

        self.menubar.addAction(self.menu_project.menuAction())
        self.menubar.addAction(self.menu_general_settings.menuAction())
        self.menubar.addAction(self.menu_plots.menuAction())
        self.menubar.addAction(self.menu_model_info.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_project.addAction(self.action_new_project)
        self.menu_project.addAction(self.action_open_project)
        self.menu_project.addAction(self.menu_recent.menuAction())
        self.menu_project.addAction(self.action_save_project)
        self.menu_project.addAction(self.action_save_project_as)
        self.menu_project.addAction(self.action_reset)
        self.menu_project.addAction(self.action_capture_image)
        self.menu_project.addSeparator()
        self.menu_project.addAction(self.action_import_geometry)
        self.menu_project.addAction(self.action_export_geometry)
        self.menu_project.addAction(self.action_import_pcf)
        self.menu_project.addAction(self.action_export_pcf)
        self.menu_project.addSeparator()
        self.menu_project.addAction(self.action_exit)
        self.menu_project.addSeparator()
        self.menu_recent.addAction(self.actionfiles)
        self.menu_plots.addAction(self.action_plot_geometry_editor)
        self.menu_plots.addAction(self.action_plot_lines)
        self.menu_plots.addAction(self.action_plot_lines_with_cross_section)
        self.menu_plots.addAction(self.action_plot_mesh)
        self.menu_plots.addAction(self.action_plot_cross_section)
        self.menu_plots.addAction(self.action_plot_material)
        self.menu_plots.addAction(self.action_plot_fluid)
        self.menu_plots.addAction(self.action_plot_default_color)
        self.menu_model_info.addAction(self.action_structural_model_info)
        self.menu_model_info.addAction(self.action_acoustic_model_info)
        self.menu_help.addAction(self.action_about_openpulse)
        self.menu_help.addAction(self.action_check_refprop)
        self.menu_general_settings.addAction(self.action_set_dark_theme)
        self.menu_general_settings.addAction(self.action_set_light_theme)
        self.menu_general_settings.addAction(self.action_user_preferences)
        self.menuTools.addAction(self.action_check_beam_criteria)
        self.menuTools.addAction(self.action_pulsation_suppression_device_editor)
        self.menuTools.addAction(self.action_pulsation_damper_editor)
        self.tool_bar.addAction(self.action_new_project)
        self.tool_bar.addAction(self.action_open_project)
        self.tool_bar.addAction(self.action_reset)
        self.tool_bar.addAction(self.action_save_project)
        self.tool_bar.addAction(self.action_save_project_as)
        self.tool_bar.addSeparator()
        self.tool_bar.addAction(self.action_zoom)
        self.tool_bar.addSeparator()
        self.tool_bar.addAction(self.action_show_mesh_data)
        self.tool_bar.addAction(self.action_show_geometry_data)
        self.tool_bar.addAction(self.action_show_lines)
        self.tool_bar.addAction(self.action_show_tubes)
        self.tool_bar.addAction(self.action_show_symbols)
        self.tool_bar.addSeparator()
        self.tool_bar.addAction(self.action_section_plane)
        self.tool_bar.addAction(self.action_show_transparent)
        self.tool_bar.addSeparator()
        self.workspaces_toolbar.addAction(self.action_geometry_editor_workspace)
        self.workspaces_toolbar.addAction(self.action_model_setup_workspace)
        self.workspaces_toolbar.addAction(self.action_results_workspace)

        self.retranslateUi(MainWindow)

        self.setup_widgets_stack.setCurrentIndex(0)
        self.render_widgets_stack.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"OpenPulse", None))
        self.action_new_project.setText(QCoreApplication.translate("MainWindow", u"New Project", None))
#if QT_CONFIG(shortcut)
        self.action_new_project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_open_project.setText(QCoreApplication.translate("MainWindow", u"Open Project", None))
#if QT_CONFIG(tooltip)
        self.action_open_project.setToolTip(QCoreApplication.translate("MainWindow", u"Open Project", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_open_project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_export_png.setText(QCoreApplication.translate("MainWindow", u"Export PNG", None))
        self.action_reset.setText(QCoreApplication.translate("MainWindow", u"Reset Project", None))
#if QT_CONFIG(shortcut)
        self.action_reset.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_project.setText(QCoreApplication.translate("MainWindow", u"Save Project", None))
#if QT_CONFIG(shortcut)
        self.action_save_project.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_project_as.setText(QCoreApplication.translate("MainWindow", u"Save Project As", None))
#if QT_CONFIG(shortcut)
        self.action_save_project_as.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_import_geometry.setText(QCoreApplication.translate("MainWindow", u"Import Geometry", None))
        self.action_import_pcf.setText(QCoreApplication.translate("MainWindow", u"Import PCF", None))
#if QT_CONFIG(tooltip)
        self.action_import_pcf.setToolTip(QCoreApplication.translate("MainWindow", u"Import Piping", None))
#endif // QT_CONFIG(tooltip)
        self.actionfiles.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.action_exit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_plot_raw_lines.setText(QCoreApplication.translate("MainWindow", u"Plot Raw Lines", None))
        self.action_plot_lines.setText(QCoreApplication.translate("MainWindow", u"Plot Lines", None))
#if QT_CONFIG(shortcut)
        self.action_plot_lines.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+2", None))
#endif // QT_CONFIG(shortcut)
        self.action_plot_mesh.setText(QCoreApplication.translate("MainWindow", u"Plot Mesh", None))
#if QT_CONFIG(shortcut)
        self.action_plot_mesh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+4", None))
#endif // QT_CONFIG(shortcut)
        self.action_plot_lines_with_cross_section.setText(QCoreApplication.translate("MainWindow", u"Plot Lines with Cross-section", None))
#if QT_CONFIG(shortcut)
        self.action_plot_lines_with_cross_section.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+3", None))
#endif // QT_CONFIG(shortcut)
        self.action_plot_cross_section.setText(QCoreApplication.translate("MainWindow", u"Plot Cross-section", None))
        self.action_plot_material.setText(QCoreApplication.translate("MainWindow", u"Plot Material", None))
        self.action_plot_fluid.setText(QCoreApplication.translate("MainWindow", u"Plot Fluid", None))
        self.action_user_preferences.setText(QCoreApplication.translate("MainWindow", u"User Preferences", None))
        self.action_plot_geometry_editor.setText(QCoreApplication.translate("MainWindow", u"Plot Geometry Editor", None))
#if QT_CONFIG(shortcut)
        self.action_plot_geometry_editor.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+1", None))
#endif // QT_CONFIG(shortcut)
        self.action_create_edit_geometry.setText(QCoreApplication.translate("MainWindow", u"Create/Edit Geometry", None))
        self.action_edit_geometry.setText(QCoreApplication.translate("MainWindow", u"Edit Geometry (GMSH GUI)", None))
        self.action_set_project_attributes.setText(QCoreApplication.translate("MainWindow", u"Set Project Attributes", None))
        self.action_set_geometry_file.setText(QCoreApplication.translate("MainWindow", u"Set Geometry File", None))
        self.action_structural_model_info.setText(QCoreApplication.translate("MainWindow", u"Structural Model Info", None))
        self.action_acoustic_model_info.setText(QCoreApplication.translate("MainWindow", u"Acoustic Model Info", None))
        self.action_check_beam_criteria.setText(QCoreApplication.translate("MainWindow", u"Beam theory validity checker", None))
        self.action_select_analysis_type.setText(QCoreApplication.translate("MainWindow", u"Select Analysis Type", None))
        self.action_analysis_setup.setText(QCoreApplication.translate("MainWindow", u"Analysis Setup", None))
        self.action_run_analysis.setText(QCoreApplication.translate("MainWindow", u"Run Analisys", None))
        self.action_plot_structural_mode_shapes.setText(QCoreApplication.translate("MainWindow", u"Plot Structural Mode Shapes", None))
        self.action_plot_displacement_field.setText(QCoreApplication.translate("MainWindow", u"Plot Displacement Field", None))
        self.action_plot_structural_frequency_response.setText(QCoreApplication.translate("MainWindow", u"Plot Structural Frequency Response", None))
        self.action_plot_reactions_frequency_response.setText(QCoreApplication.translate("MainWindow", u"Plot Reactions Frequency Response", None))
        self.action_plot_stress_field.setText(QCoreApplication.translate("MainWindow", u"Plot Stress Field", None))
        self.action_plot_stress_frequency_response.setText(QCoreApplication.translate("MainWindow", u"Plot Stress Frequency Response", None))
        self.action_plot_acoustic_pressure_field.setText(QCoreApplication.translate("MainWindow", u"Plot Acoustic Pressure Field", None))
        self.action_plot_acoustic_frequency_response.setText(QCoreApplication.translate("MainWindow", u"Plot Acoustic Frequency Response", None))
        self.action_plot_acoustic_frequency_response_function.setText(QCoreApplication.translate("MainWindow", u"Plot Acoustic Frequency Response Function", None))
        self.acoustic_plot_acoustic_delta_pressures.setText(QCoreApplication.translate("MainWindow", u"Plot Acoustic Delta Pressures", None))
        self.action_plot_transmission_loss_or_attenuation.setText(QCoreApplication.translate("MainWindow", u"Plot Ransmission Loss or Attenuation", None))
        self.action_play_pause_animation.setText(QCoreApplication.translate("MainWindow", u"Play/Pause Animation", None))
        self.action_animation_settings.setText(QCoreApplication.translate("MainWindow", u"Animation Settings", None))
        self.action_help.setText(QCoreApplication.translate("MainWindow", u"Help", None))
#if QT_CONFIG(shortcut)
        self.action_help.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.action_about_openpulse.setText(QCoreApplication.translate("MainWindow", u"About OpenPulse", None))
        self.action_show_mesh_data.setText(QCoreApplication.translate("MainWindow", u"Show Mesh Data", None))
#if QT_CONFIG(tooltip)
        self.action_show_mesh_data.setToolTip(QCoreApplication.translate("MainWindow", u"Show Mesh Data", None))
#endif // QT_CONFIG(tooltip)
        self.action_show_lines.setText(QCoreApplication.translate("MainWindow", u"Show Lines", None))
        self.action_show_tubes.setText(QCoreApplication.translate("MainWindow", u"Show Tubes", None))
        self.action_show_symbols.setText(QCoreApplication.translate("MainWindow", u"Show Symbols", None))
        self.action_hide_selection.setText(QCoreApplication.translate("MainWindow", u"Hide Selection", None))
        self.action_unhide_all.setText(QCoreApplication.translate("MainWindow", u"Unhide All", None))
        self.action_export_geometry.setText(QCoreApplication.translate("MainWindow", u"Export Geometry", None))
#if QT_CONFIG(tooltip)
        self.action_export_geometry.setToolTip(QCoreApplication.translate("MainWindow", u"Export Geometry", None))
#endif // QT_CONFIG(tooltip)
        self.action_set_dark_theme.setText(QCoreApplication.translate("MainWindow", u"Use dark theme", None))
        self.action_set_light_theme.setText(QCoreApplication.translate("MainWindow", u"Use light theme", None))
        self.action_remove_themes.setText(QCoreApplication.translate("MainWindow", u"Remove themes", None))
        self.action_show_transparent.setText(QCoreApplication.translate("MainWindow", u"Show Transparent", None))
        self.action_select_elements.setText(QCoreApplication.translate("MainWindow", u"Selection to Elements", None))
#if QT_CONFIG(tooltip)
        self.action_select_elements.setToolTip(QCoreApplication.translate("MainWindow", u"Selection to Elements", None))
#endif // QT_CONFIG(tooltip)
        self.action_export_pcf.setText(QCoreApplication.translate("MainWindow", u"Export PCF", None))
        self.action_geometry_editor_help.setText(QCoreApplication.translate("MainWindow", u"Geometry Editor Help", None))
        self.action_section_plane.setText(QCoreApplication.translate("MainWindow", u"Section Plane", None))
        self.action_zoom.setText(QCoreApplication.translate("MainWindow", u"Zoom", None))
#if QT_CONFIG(tooltip)
        self.action_zoom.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom To Fit", None))
#endif // QT_CONFIG(tooltip)
        self.action_pulsation_suppression_device_editor.setText(QCoreApplication.translate("MainWindow", u"Pulsation suppression device editor", None))
        self.action_show_geometry_data.setText(QCoreApplication.translate("MainWindow", u"Show Geometry Data", None))
#if QT_CONFIG(tooltip)
        self.action_show_geometry_data.setToolTip(QCoreApplication.translate("MainWindow", u"Show Geometry Data", None))
#endif // QT_CONFIG(tooltip)
        self.action_plot_default_color.setText(QCoreApplication.translate("MainWindow", u"Plot Default Color", None))
        self.action_geometry_editor_workspace.setText(QCoreApplication.translate("MainWindow", u"Geometry", None))
#if QT_CONFIG(tooltip)
        self.action_geometry_editor_workspace.setToolTip(QCoreApplication.translate("MainWindow", u"Geometry editor workspace", None))
#endif // QT_CONFIG(tooltip)
        self.action_model_setup_workspace.setText(QCoreApplication.translate("MainWindow", u"Model", None))
#if QT_CONFIG(tooltip)
        self.action_model_setup_workspace.setToolTip(QCoreApplication.translate("MainWindow", u"Model setup workspace", None))
#endif // QT_CONFIG(tooltip)
        self.action_results_workspace.setText(QCoreApplication.translate("MainWindow", u"Results", None))
#if QT_CONFIG(tooltip)
        self.action_results_workspace.setToolTip(QCoreApplication.translate("MainWindow", u"Results workspace", None))
#endif // QT_CONFIG(tooltip)
        self.action_check_refprop.setText(QCoreApplication.translate("MainWindow", u"Check REFPROP", None))
        self.action_pulsation_damper_editor.setText(QCoreApplication.translate("MainWindow", u"Pulsation damper editor", None))
        self.action_capture_image.setText(QCoreApplication.translate("MainWindow", u"Capture Image", None))
        self.menu_project.setTitle(QCoreApplication.translate("MainWindow", u"Project", None))
        self.menu_recent.setTitle(QCoreApplication.translate("MainWindow", u"Recent Projects", None))
        self.menu_plots.setTitle(QCoreApplication.translate("MainWindow", u"Plots", None))
        self.menu_model_info.setTitle(QCoreApplication.translate("MainWindow", u"Model Info", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menu_general_settings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.tool_bar.setWindowTitle(QCoreApplication.translate("MainWindow", u"Main toolbar", None))
        self.workspaces_toolbar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi



class MainWindow_UI(QMainWindow, Ui_MainWindow):
    """
    Component Hierarchy:
    - MainWindow: QMainWindow
        - centralwidget: QWidget
            - (Layout): QVBoxLayout
                    - splitter: QSplitter
                        - setup_widgets_stack: QStackedWidget
                            - page: QWidget
                            - page_2: QWidget
                        - render_widgets_stack: QStackedWidget
                            - page_3: QWidget
                            - page_4: QWidget
        - menubar: QMenuBar
            - menu_project: QMenu
                - menu_recent: QMenu
            - menu_plots: QMenu
            - menu_model_info: QMenu
            - menu_help: QMenu
            - menu_general_settings: QMenu
            - menuTools: QMenu
        - statusbar: QStatusBar
        - tool_bar: QToolBar
        - workspaces_toolbar: QToolBar
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
