from unv_reader import unvReader

import time
import os 

from tempfile import mkdtemp
from platform import system 
import subprocess 

class FemMesh:
    def __init__(self, path, min_len=0, max_len=0):
        self.edges = dict()
        self.vertices = dict()
        self.edges_matrix = []
        self.vertices_matrix = []
        
        self.file_path = path
        self.min_len = min_len
        self.max_len = max_len or '1e+06'

        self.temp_dir = None
        self.temp_geo = None
        self.temp_unv = None
        self.gmsh_command = None

        self.get_temp_paths()
        self.create_geo_file()
        self.get_gmsh_command()
        self.run_gmsh()
        self.read_unv()

    def get_temp_paths(self):
        self.temp_dir = mkdtemp(prefix='fem_mesh')
        self.temp_geo = self.temp_dir + '\\geometry.geo'
        self.temp_unv = self.temp_dir + '\\geometry.unv'

    def create_geo_file(self):
        with open(self.temp_geo, 'w') as file:
            file.write('//Geo file generated by PETRO AIV' + '\n')
            file.write('\n')
            file.write('Merge "{}";\n'.format(self.file_path))
            file.write('Mesh.CharacteristicLengthMax = {};\n'.format(self.max_len))
            file.write('Mesh.CharacteristicLengthMin = {};\n'.format(self.min_len))
            file.write('Mesh.Optimize = 1;\n')
            file.write('Mesh.OptimizeNetgen = 0;\n')
            file.write('Mesh.HighOrderOptimize = 0;\n')
            file.write('Mesh.ElementOrder = 1;\n')
            file.write('Mesh.Algorithm = 2;\n')
            file.write('Mesh.Algorithm3D = 1;\n')
            file.write('\n')
            file.write('Geometry.Tolerance = 1e-06;\n')
            file.write('Mesh  3;\n')
            file.write('Coherence Mesh;\n')
            file.write('\n')
            file.write('Mesh.Format = 2;\n')
            file.write('Mesh.SaveAll = 1;\n')
            file.write('Save "{}";\n'.format(self.temp_unv))

    def get_gmsh_command(self):
        if system() == 'Windows':
            self.gmsh_command = 'vendor\\gmsh-4.4.1-Windows32-sdk\\bin\\gmsh.exe'
        elif system() == 'Linux':
            self.gmsh_command = 'gmsh'
            
    def run_gmsh(self):
        commandlist = [self.gmsh_command, '-', self.temp_geo]
        subprocess.call(commandlist, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    def read_unv(self):
        unv = unvReader(self.temp_unv)
        self.edges = unv.edges
        self.vertices = unv.vertices
        self.vertices_matrix = unv.get_vertice_matrix()
        self.edges_matrix = unv.get_edges_matrix()

