# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Repositorios\OpenPulse\pulse\left_menu_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 659)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.bottom_widget = QtWidgets.QWidget(Form)
        self.bottom_widget.setMinimumSize(QtCore.QSize(0, 120))
        self.bottom_widget.setObjectName("bottom_widget")
        self.gridLayout.addWidget(self.bottom_widget, 1, 0, 1, 1)
        self.top_widget = QtWidgets.QWidget(Form)
        self.top_widget.setMinimumSize(QtCore.QSize(0, 120))
        self.top_widget.setObjectName("top_widget")
        self.gridLayout.addWidget(self.top_widget, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
