# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kula\Petrobras\temp1\OpenPulse\data\user_input\ui\Model\Setup\Acoustic\acousticElementTypeInput.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(400, 467)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 467))
        Dialog.setMaximumSize(QtCore.QSize(400, 467))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setWhatsThis("")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 56, 400, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.tabWidget_general = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget_general.setGeometry(QtCore.QRect(10, 10, 383, 391))
        self.tabWidget_general.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_general.setMaximumSize(QtCore.QSize(16777215, 10000000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tabWidget_general.setFont(font)
        self.tabWidget_general.setObjectName("tabWidget_general")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.pushButton_confirm = QtWidgets.QPushButton(self.tab_setup)
        self.pushButton_confirm.setGeometry(QtCore.QRect(120, 310, 121, 32))
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(121, 32))
        self.pushButton_confirm.setMaximumSize(QtCore.QSize(121, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.lineEdit_selected_ID = QtWidgets.QLineEdit(self.tab_setup)
        self.lineEdit_selected_ID.setEnabled(True)
        self.lineEdit_selected_ID.setGeometry(QtCore.QRect(136, 20, 220, 30))
        self.lineEdit_selected_ID.setMinimumSize(QtCore.QSize(220, 30))
        self.lineEdit_selected_ID.setMaximumSize(QtCore.QSize(220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_selected_ID.setFont(font)
        self.lineEdit_selected_ID.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_selected_ID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 255);")
        self.lineEdit_selected_ID.setText("")
        self.lineEdit_selected_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_selected_ID.setObjectName("lineEdit_selected_ID")
        self.label_3 = QtWidgets.QLabel(self.tab_setup)
        self.label_3.setGeometry(QtCore.QRect(14, 22, 120, 26))
        self.label_3.setMinimumSize(QtCore.QSize(120, 26))
        self.label_3.setMaximumSize(QtCore.QSize(120, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tabWidget_element_type = QtWidgets.QTabWidget(self.tab_setup)
        self.tabWidget_element_type.setGeometry(QtCore.QRect(16, 70, 349, 231))
        self.tabWidget_element_type.setObjectName("tabWidget_element_type")
        self.tab_type = QtWidgets.QWidget()
        self.tab_type.setObjectName("tab_type")
        self.label_2 = QtWidgets.QLabel(self.tab_type)
        self.label_2.setGeometry(QtCore.QRect(20, 103, 305, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setMidLineWidth(0)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_type)
        self.comboBox.setGeometry(QtCore.QRect(70, 143, 200, 30))
        self.comboBox.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("")
        self.comboBox.setMaxCount(500)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox_flow_effects = QtWidgets.QCheckBox(self.tab_type)
        self.checkBox_flow_effects.setGeometry(QtCore.QRect(20, 12, 231, 21))
        self.checkBox_flow_effects.setObjectName("checkBox_flow_effects")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_type)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 40, 341, 41))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lineEdit_vol_flow = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_vol_flow.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vol_flow.sizePolicy().hasHeightForWidth())
        self.lineEdit_vol_flow.setSizePolicy(sizePolicy)
        self.lineEdit_vol_flow.setMinimumSize(QtCore.QSize(120, 24))
        self.lineEdit_vol_flow.setMaximumSize(QtCore.QSize(100, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lineEdit_vol_flow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_vol_flow.setFont(font)
        self.lineEdit_vol_flow.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_vol_flow.setText("")
        self.lineEdit_vol_flow.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vol_flow.setObjectName("lineEdit_vol_flow")
        self.verticalLayout_17.addWidget(self.lineEdit_vol_flow)
        self.gridLayout_6.addLayout(self.verticalLayout_17, 0, 1, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_18.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_vol_flow = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_vol_flow.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_vol_flow.sizePolicy().hasHeightForWidth())
        self.label_vol_flow.setSizePolicy(sizePolicy)
        self.label_vol_flow.setMinimumSize(QtCore.QSize(140, 35))
        self.label_vol_flow.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_vol_flow.setFont(font)
        self.label_vol_flow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vol_flow.setObjectName("label_vol_flow")
        self.verticalLayout_18.addWidget(self.label_vol_flow)
        self.gridLayout_6.addLayout(self.verticalLayout_18, 0, 0, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_ms_unit = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_ms_unit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ms_unit.sizePolicy().hasHeightForWidth())
        self.label_ms_unit.setSizePolicy(sizePolicy)
        self.label_ms_unit.setMinimumSize(QtCore.QSize(45, 25))
        self.label_ms_unit.setMaximumSize(QtCore.QSize(45, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_ms_unit.setFont(font)
        self.label_ms_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ms_unit.setObjectName("label_ms_unit")
        self.verticalLayout_19.addWidget(self.label_ms_unit)
        self.gridLayout_6.addLayout(self.verticalLayout_19, 0, 2, 1, 1)
        self.tabWidget_element_type.addTab(self.tab_type, "")
        self.tab_damping = QtWidgets.QWidget()
        self.tab_damping.setObjectName("tab_damping")
        self.label_109 = QtWidgets.QLabel(self.tab_damping)
        self.label_109.setEnabled(True)
        self.label_109.setGeometry(QtCore.QRect(60, 60, 101, 21))
        self.label_109.setMinimumSize(QtCore.QSize(101, 21))
        self.label_109.setMaximumSize(QtCore.QSize(101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_109.setFont(font)
        self.label_109.setMouseTracking(True)
        self.label_109.setAlignment(QtCore.Qt.AlignCenter)
        self.label_109.setObjectName("label_109")
        self.lineEdit_proportional_damping = QtWidgets.QLineEdit(self.tab_damping)
        self.lineEdit_proportional_damping.setEnabled(True)
        self.lineEdit_proportional_damping.setGeometry(QtCore.QRect(186, 70, 100, 26))
        self.lineEdit_proportional_damping.setMinimumSize(QtCore.QSize(100, 26))
        self.lineEdit_proportional_damping.setMaximumSize(QtCore.QSize(100, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_proportional_damping.setFont(font)
        self.lineEdit_proportional_damping.setText("")
        self.lineEdit_proportional_damping.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_proportional_damping.setObjectName("lineEdit_proportional_damping")
        self.label_5 = QtWidgets.QLabel(self.tab_damping)
        self.label_5.setGeometry(QtCore.QRect(36, 18, 269, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setMidLineWidth(0)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_110 = QtWidgets.QLabel(self.tab_damping)
        self.label_110.setEnabled(True)
        self.label_110.setGeometry(QtCore.QRect(288, 68, 40, 30))
        self.label_110.setMinimumSize(QtCore.QSize(40, 30))
        self.label_110.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_110.setFont(font)
        self.label_110.setMouseTracking(True)
        self.label_110.setAlignment(QtCore.Qt.AlignCenter)
        self.label_110.setObjectName("label_110")
        self.label_111 = QtWidgets.QLabel(self.tab_damping)
        self.label_111.setEnabled(True)
        self.label_111.setGeometry(QtCore.QRect(67, 80, 81, 21))
        self.label_111.setMinimumSize(QtCore.QSize(81, 21))
        self.label_111.setMaximumSize(QtCore.QSize(81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_111.setFont(font)
        self.label_111.setMouseTracking(True)
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.tabWidget_element_type.addTab(self.tab_damping, "")
        self.tabWidget_general.addTab(self.tab_setup, "")
        self.tab_details = QtWidgets.QWidget()
        self.tab_details.setObjectName("tab_details")
        self.pushButton_get_information = QtWidgets.QPushButton(self.tab_details)
        self.pushButton_get_information.setGeometry(QtCore.QRect(269, 315, 90, 30))
        self.pushButton_get_information.setMinimumSize(QtCore.QSize(90, 29))
        self.pushButton_get_information.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_get_information.setFont(font)
        self.pushButton_get_information.setObjectName("pushButton_get_information")
        self.treeWidget_element_type = QtWidgets.QTreeWidget(self.tab_details)
        self.treeWidget_element_type.setGeometry(QtCore.QRect(12, 58, 352, 291))
        self.treeWidget_element_type.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget_element_type.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.treeWidget_element_type.setFont(font)
        self.treeWidget_element_type.setIndentation(0)
        self.treeWidget_element_type.setObjectName("treeWidget_element_type")
        self.treeWidget_element_type.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.treeWidget_element_type.headerItem().setFont(0, font)
        self.treeWidget_element_type.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.treeWidget_element_type.headerItem().setFont(1, font)
        self.label_4 = QtWidgets.QLabel(self.tab_details)
        self.label_4.setGeometry(QtCore.QRect(28, 16, 80, 26))
        self.label_4.setMinimumSize(QtCore.QSize(80, 26))
        self.label_4.setMaximumSize(QtCore.QSize(80, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_selected_group = QtWidgets.QLineEdit(self.tab_details)
        self.lineEdit_selected_group.setEnabled(False)
        self.lineEdit_selected_group.setGeometry(QtCore.QRect(110, 14, 220, 30))
        self.lineEdit_selected_group.setMinimumSize(QtCore.QSize(220, 30))
        self.lineEdit_selected_group.setMaximumSize(QtCore.QSize(220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_selected_group.setFont(font)
        self.lineEdit_selected_group.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_selected_group.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_selected_group.setText("")
        self.lineEdit_selected_group.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_selected_group.setObjectName("lineEdit_selected_group")
        self.treeWidget_element_type.raise_()
        self.pushButton_get_information.raise_()
        self.label_4.raise_()
        self.lineEdit_selected_group.raise_()
        self.tabWidget_general.addTab(self.tab_details, "")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 57))
        self.frame.setMinimumSize(QtCore.QSize(400, 57))
        self.frame.setMaximumSize(QtCore.QSize(450, 57))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(8, 14, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(266, 0, 130, 58))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_all = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_all.setEnabled(True)
        self.radioButton_all.setMinimumSize(QtCore.QSize(128, 24))
        self.radioButton_all.setMaximumSize(QtCore.QSize(128, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.radioButton_all.setFont(font)
        self.radioButton_all.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_all.setChecked(True)
        self.radioButton_all.setObjectName("radioButton_all")
        self.verticalLayout_2.addWidget(self.radioButton_all)
        self.radioButton_selection = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_selection.setMinimumSize(QtCore.QSize(128, 24))
        self.radioButton_selection.setMaximumSize(QtCore.QSize(128, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.radioButton_selection.setFont(font)
        self.radioButton_selection.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_selection.setChecked(False)
        self.radioButton_selection.setObjectName("radioButton_selection")
        self.verticalLayout_2.addWidget(self.radioButton_selection)

        self.retranslateUi(Dialog)
        self.tabWidget_general.setCurrentIndex(0)
        self.tabWidget_element_type.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", " Set: acoustic element type"))
        self.pushButton_confirm.setText(_translate("Dialog", "Confirm"))
        self.label_3.setText(_translate("Dialog", "Selected lines:"))
        self.label_2.setText(_translate("Dialog", "Choose an acoustic element type:"))
        self.comboBox.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.comboBox.setCurrentText(_translate("Dialog", "  Undamped"))
        self.comboBox.setItemText(0, _translate("Dialog", "  Undamped"))
        self.comboBox.setItemText(1, _translate("Dialog", "  Proportional"))
        self.comboBox.setItemText(2, _translate("Dialog", "  Wide-duct"))
        self.comboBox.setItemText(3, _translate("Dialog", "  LRF fluid equivalent"))
        self.comboBox.setItemText(4, _translate("Dialog", "  LRF full"))
        self.checkBox_flow_effects.setText(_translate("Dialog", "Include flow effects"))
        self.label_vol_flow.setText(_translate("Dialog", "Volume flow rate"))
        self.label_ms_unit.setText(_translate("Dialog", "[m³/s]"))
        self.tabWidget_element_type.setTabText(self.tabWidget_element_type.indexOf(self.tab_type), _translate("Dialog", "Type"))
        self.label_109.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">proportional</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Insert a value to the damping:"))
        self.label_110.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">[ - ]</p></body></html>"))
        self.label_111.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:600; font-style:italic;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">coefficient</span></p></body></html>"))
        self.tabWidget_element_type.setTabText(self.tabWidget_element_type.indexOf(self.tab_damping), _translate("Dialog", "Damping"))
        self.tabWidget_general.setTabText(self.tabWidget_general.indexOf(self.tab_setup), _translate("Dialog", "Setup"))
        self.pushButton_get_information.setText(_translate("Dialog", "See details"))
        self.treeWidget_element_type.headerItem().setText(0, _translate("Dialog", "Element type"))
        self.treeWidget_element_type.headerItem().setText(1, _translate("Dialog", "Lines"))
        self.label_4.setText(_translate("Dialog", "Group"))
        self.tabWidget_general.setTabText(self.tabWidget_general.indexOf(self.tab_details), _translate("Dialog", "Details"))
        self.label.setText(_translate("Dialog", "Attribute element type to:"))
        self.radioButton_all.setText(_translate("Dialog", "All lines"))
        self.radioButton_selection.setText(_translate("Dialog", "Selected lines"))
