# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kula\Petrobras\temp3\OpenPulse\data\user_input\ui\Plots\Messages\printMessages.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 350)
        Dialog.setMinimumSize(QtCore.QSize(600, 350))
        Dialog.setMaximumSize(QtCore.QSize(600, 350))
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 52, 600, 298))
        self.frame_2.setMinimumSize(QtCore.QSize(600, 298))
        self.frame_2.setMaximumSize(QtCore.QSize(600, 298))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.Label_message = QtWidgets.QLabel(self.frame_2)
        self.Label_message.setGeometry(QtCore.QRect(10, 12, 580, 230))
        self.Label_message.setMinimumSize(QtCore.QSize(580, 230))
        self.Label_message.setMaximumSize(QtCore.QSize(580, 230))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Label_message.setFont(font)
        self.Label_message.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Label_message.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_message.setTextFormat(QtCore.Qt.AutoText)
        self.Label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_message.setWordWrap(True)
        self.Label_message.setObjectName("Label_message")
        self.pushButton_close = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_close.setGeometry(QtCore.QRect(250, 252, 100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setDefault(False)
        self.pushButton_close.setFlat(False)
        self.pushButton_close.setObjectName("pushButton_close")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 600, 53))
        self.frame_4.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setGeometry(QtCore.QRect(10, 8, 580, 38))
        self.frame.setMinimumSize(QtCore.QSize(580, 0))
        self.frame.setMaximumSize(QtCore.QSize(580, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Label_title = QtWidgets.QLabel(self.frame)
        self.Label_title.setGeometry(QtCore.QRect(4, 6, 573, 29))
        self.Label_title.setMinimumSize(QtCore.QSize(573, 0))
        self.Label_title.setMaximumSize(QtCore.QSize(573, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Label_title.setFont(font)
        self.Label_title.setTextFormat(QtCore.Qt.AutoText)
        self.Label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_title.setObjectName("Label_title")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Label_message.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">message</span></p></body></html>"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))
        self.Label_title.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">TITLE</span></p></body></html>"))
