# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kula\Petrobras\OpenPulse\data\user_input\ui\Analysis\runAnalysisInput2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 450)
        self.frame_message = QtWidgets.QFrame(Form)
        self.frame_message.setGeometry(QtCore.QRect(0, 50, 600, 400))
        self.frame_message.setMinimumSize(QtCore.QSize(600, 400))
        self.frame_message.setMaximumSize(QtCore.QSize(600, 400))
        self.frame_message.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_message.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_message.setObjectName("frame_message")
        self.label_message = QtWidgets.QLabel(self.frame_message)
        self.label_message.setGeometry(QtCore.QRect(6, 6, 589, 389))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_message.setFont(font)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.frame_title = QtWidgets.QFrame(Form)
        self.frame_title.setGeometry(QtCore.QRect(0, 0, 600, 51))
        self.frame_title.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_title.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_title.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_title.setLineWidth(1)
        self.frame_title.setObjectName("frame_title")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setGeometry(QtCore.QRect(6, 6, 589, 39))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_message.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#0000ff;\">Solution in progress…</span></p></body></html>"))
        self.label_title.setText(_translate("Form", "Run analysis"))
