from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QApplication

from opps.interface.toolboxes import GeometryToolbox
from pulse.interface.main_window import MainWindow

from pulse.project import Project
from pulse.uix.config import Config

class Application(QApplication):
    selection_changed = pyqtSignal()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # global params
        self.config = Config()
        self.project = Project()
        self.geometry_toolbox = GeometryToolbox()

        # gui
        self.main_window = MainWindow()
        self.close_splash()
        self.main_window.configure_window()
        self.main_window.show()
        self.update()

    def close_splash(self):
        # If it is an executable generated by pyinstaller 
        # and it has a splash screen close it
        try:
            import pyi_splash
            pyi_splash.close()
        except:
            pass


    def update(self):
        self.geometry_toolbox.update()
        self.main_window.update()
